#DIRECTORIO DE TRABAJO
RUTA <- "C:/Users/yasuv/OneDrive/Documentos/PAQ  R/BD1.csv"

DATOS <- read.csv(RUTA)
print(DATOS)

#CARGO DE LIBRERIA
library(CCOMBOY)
#  FUNCIÓN Y DECLARACION DE VARIABLES

CCBOVin(PESO1=DATOS$PESO1, PDESV=DATOS$PDESV, SEXO=DATOS$SEXO, ALTURA=DATOS$ALTURA,PESOF=DATOS$PESO.FIN, GD=DATOS$GD, DAL=DATOS$DAL, Fsex=DATOS$F.SEXO)
